apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: k9798909/backend-service
        ports:
        - containerPort: 8088
        env:
          - name: jwt.secret.key
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: secretKey
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-app
  template:
    metadata:
      labels:
        app: shop-app
    spec:
      containers:
      - name: shop-app
        image: k9798909/shop-app
        ports:
        - containerPort: 8080
